"""Add Completed Col

Revision ID: 61f26d0a44e0
Revises: d623be675bc8
Create Date: 2020-05-08 13:46:09.773079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f26d0a44e0'
down_revision = 'd623be675bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos',
    sa.Column('completed', sa.Boolean(), nullable=True)
    )

    op.execute('UPDATE todos SET completed = FALSE WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
